### ISSUE TITLE
Message AVPs are stored in a slice

### ISSUE THREAD

**Issue by taseppa** [fiorix/go-diameter#12]
Currently message AVPs are stored in a slice but wouldn't multi-key dictionary be more appropriate data structure? This would make finding of AVPs faster. Also removal of AVPs will be easier (which seems not to be supported at all).

**Comment by fiorix** [comment]
Yes, a map may be more appropriate for finding messages indeed. The values would still have to be a slice since you can have multiples of the same AVP in certain messages, and this would require changing the GroupedAVP as well to inherit that logic.

However, having a map wouldn't work for building messages since it requires that your AVPs are sent in a certain order.

I don't see the rationale for removing AVPs from a message, why would you want that? Basically once you receive a message you only "use" it, and if you have to reply to it you'd call `a := m.Answer(ResultCode)` then add your response AVPs into the newly created `a` message.

If you're struggling with the `FindAVP` stuff you should definitely give that up and use reflection, like Go does with parsing JSON and XML. That allows for you to read up the AVPs you need into a data structure of your own without any pain. See https://github.com/fiorix/go-diameter/blob/master/diam/reflect_test.go for examples.

Will close this for now but will consider having the AVPs indexed in a map for faster lookups. It'd use more memory but maybe worth comparing to the current implementation since `FindAVP` and friends would be faster. All those are measured in the test benchmarks and I keep track of performance very tightly.
