### ISSUE TITLE
If AVP is not found in dictionary server disconnects the client

### ISSUE THREAD

**Issue by taseppa** [fiorix/go-diameter#13]
This seems like a very extreme measure. According to RFC 6733: 

   o  A request with an unrecognized AVP is received with the 'M' bit
      (Mandatory bit) set causes an answer to be sent with the Result-
      Code AVP set to DIAMETER_AVP_UNSUPPORTED and the Failed-AVP AVP
      containing the offending AVP.

This functionality can't be currently implemented if client is disconnected.

Ideally only AVPs present in the dictionary are parsed but when the message is forwarded again, also the missing AVPS are present. This might need considerable refactoring in the code? Simpler solution would be to at least return an error instead of disconnecting the client.

**Comment by fiorix** [comment]
The example client and server are definitely not compliant with the RFC and are only there so others can actually have an idea of how to write a client and server. Those exist since the early versions of this package when I still hadn't decided on the API etc, so feel free to submit patches or at some point I will fix them both.

FWIW this is how I've been writing them lately (apart from the test bits): https://github.com/fiorix/go-diameter/blob/master/diam/serve_test.go
