### ISSUE TITLE
Called-Station-Id AVP definition missing

### ISSUE THREAD

**Issue by taseppa** [fiorix/go-diameter#20]
Seems like only the rule 	<rule avp="Called-Station-Id" required="false" max="1"/> is added but definition is missing which causes the application to fail processing a message that contains such AVP.

I wonder what process has been used to create the dictionary (xml) files, maybe there could be some other missing AVP definitions?

**Comment by fiorix** [comment]
I see the rule defined but this AVP isn't defined neither in RFC 6733 or RFC 4006. FWIW it doesn't have to be in the built-in dictionary, you can load your own on top of it. See the examples/client and server.

**Comment by taseppa** [comment]
Yeah it's actually a 3GPP specific AVP and should be defined in tgpp_ro_rf.xml. By doing some blind testing all AVP rules I tested had a corresponding definition, so far this is the only AVP I have noticed that is missing a definition.

**Comment by fiorix** [comment]
Ok, so we didn't use any particular script for creating the dictionaries. If you define a new AVP in the xml files in `diam/dict/testdata` and run the `diam/autogen.sh` script, it will be added to generated files. You can check by looking at `avp/codes.go` afterwards.

If you search the git log you'll find the TS.xxx spec for reference.

∀

**Comment by jaroszan** [comment]
Called-Station-Id actually belongs to Network Access Server Application (https://tools.ietf.org/html/rfc7155 or previously 4005). 

Not all avps which have a rule in Ro-Rf dictionary are defined in that file, some refer to Credit-Control application and since credit-control dictionary is preloaded you don't have that problem. 

I think a better approach would be to define a separate dictionary for NAS and maybe preload it as well?

**Comment by fiorix** [comment]
Yes, that's definitely better. If the `dict.Default` dictionary becomes too bloated it may degrade performance of applications that don't need Ro-Rf though. Gotta see how many more AVPs this new one brings in.
