### ISSUE TITLE
Message.WriteTo panics for uint32 before string in group AVP

### ISSUE THREAD

**Issue by danbogos** [fiorix/go-diameter#36]
Hi,

I have hit a panic on normal usage, adding vendor AVPs in a group and trying to send them over network.

Before trying to figure it out by myself, is there any easy/obvious fix for my issue?

Have done a simplified test for my issue here:
https://github.com/cgrates/go-diameter/blob/master/diam/message_test.go#L185

I should mention that adding string before int works just fine and also if int is the last one in group. The only issue is when string follows int.

Thanks in advance!
DanB

**Comment by fiorix** [comment]
The output on Jenkins shows the problem is on avp.go line 163, which does not exist, and happens there when we run test -cover, which instruments the code. So I fetched your test code and ran again, and it shows crashing here:

https://github.com/fiorix/go-diameter/blob/master/diam/avp.go#L130

It is related to the VendorID, which might not be populated when we try to encode. Still unclear why that happens but I'll investigate more.

**Comment by danbogos** [comment]
Appreciated. If we can help, let me know. We also got the panic in the same place.

DanB

**Comment by fiorix** [comment]
Please try this one, it should fix the problem.

**Comment by danbogos** [comment]
Many thanks!!! It works now.

DanB

**Comment by fiorix** [comment]
I've put a minor fix there to ensure we never crash because of this. It is possible that people will create AVPs manually instead of using NewAVP, and in that case, it is their responsibility to set the V bit when they set a VendorID in the AVP. This check looks at the flags not VendorID when computing the size in bytes for the AVP during serialization.

**Comment by danbogos** [comment]
Great!

DanB
