### ISSUE TITLE
do not support connecting to relay agent?

### ISSUE THREAD

**Issue by kingluo** [fiorix/go-diameter#46]
When I use the example client to connect the relay agent, it exits with error:
`auth application 4294967295 is not supported`

The CEA from relay agent includes the relay application id:
`AVP: Auth-Application-Id(258) l=12 f=-M- val=Relay (4294967295)`

The relay agent is very standard network entity in diameter network, so does go-diameter supports it?

**Comment by fiorix** [comment]
Programs written with `go-diameter` can definitely connect to relay agents. They can as *be* relay agents, since `go-diameter` is a programming framework.

However, you have to provide it with the right dictionaries to do so. The example client does not support the relay dictionary out of the box, but you can modify it.

**Comment by kingluo** [comment]
Thank you.

I add below xml to make it support relay agent:

`<application id="4294967295"></application>`

Why not put it into default dictionary?

**Comment by fiorix** [comment]
Cool. It's not in the dictionary because nobody else needed so far. If you put there and send a pull request I'll merge it. Thanks! ;)
